タイトルシーンの修正・実装
ilovejikkenjisshu/ILJJ_Mk-XV pull request #12
Opened 2019-12-02 02:38 UTC by chuyii

タイトルシーンを実装。
Canvasを用いてタイトルとボタンの描画を行う。
TitleManagerにアタッチしたスタートボタンをクリックすることでSimpleStageSceneに遷移。

close #5

2019-12-02 17:57 UTC, GarAcT reviewed
動かしてみたけど動作としては問題ないです

![Desktop Screenshot 2019 12 03 - 02 55 04 05](https://user-images.githubusercontent.com/16851181/69982746-8d5a8500-1578-11ea-8236-2fa48d199c23.png)

2019-12-02 17:57 UTC, GarAcT commented on Assets/Scripts/TitleManager.cs
> +        Button startButton = m_StartButton.GetComponent<Button>();
`m_StartButton` と `startButton` が別々になっている意図がイマイチピンと来ない (こういうもんなのか知らないのでなんとも言えない)…

2019-12-02 18:14 UTC, GarAcT requested changes
（そこまで辿り着けるかわからんが）マルチプレイヤーも視野に入れているはずなので、もう少し拡張性というか後からいじくりやすい方が良いなぁと思いました

2019-12-02 18:14 UTC, GarAcT commented on Assets/Scripts/TitleManager.cs
> +        SceneManager.LoadScene("SimpleStageScene");
ここもあとから設定可能な方がいいな :heart:

2019-12-02 23:19 UTC, chuyii commented on Assets/Scripts/TitleManager.cs
> +        Button startButton = m_StartButton.GetComponent<Button>();
[ここ](https://docs.unity3d.com/ja/current/ScriptReference/UI.Button-onClick.html)のexampleを参考にしてみたの。

2019-12-02 23:19 UTC, chuyii commented
ButtonのonClickに直接設定できるのは把握していたんだけど、タイトル部分の処理で何か増やす時にまとまっていたほうがいいかなと思ってTitleManagerに書いてました。

言われてみればメリットは無さそうなので、Buttonに直接指定するように書き直します。

2019-12-02 23:20 UTC, chuyii commented on Assets/Scripts/TitleManager.cs
> +        SceneManager.LoadScene("SimpleStageScene");
Inspectorからシーンを変数に指定できるようにしたほうがいいってことか。
確かに！変更しておきます

2019-12-04 01:17 UTC, GarAcT approved these changes
おっけーです

2019-12-04 01:19 UTC, merged