[update] TitleSchene.unity
ilovejikkenjisshu/ILJJ_Mk-XV pull request #17
Opened 2020-02-10 12:47 UTC by proelbtn

2020-02-10 23:58 UTC, GarAcT commented
fixのcommit、まだpushされてない？

2020-02-11 06:43 UTC, GarAcT requested changes
Fix that Quit button doesn't work

2020-02-11 15:01 UTC, proelbtn commented
Okay, I'll fix it.

2020-02-11 15:14 UTC, proelbtn commented
fixed

2020-02-11 15:18 UTC, GarAcT commented
StartButtonになんか変なScriptの残骸がAttachされてるのでそれだけなおして

2020-02-11 15:34 UTC, proelbtn commented
fixed

2020-02-11 15:43 UTC, GarAcT approved these changes

2020-02-11 15:44 UTC, GarAcT commented
他の方々のレビューがないがmergeしちゃう？

2020-02-12 00:12 UTC, Semi11 approved these changes

2020-02-12 02:34 UTC, chuyii approved these changes

2020-02-12 02:43 UTC, merged