[add] サイコロを振る
ilovejikkenjisshu/ILJJ_Mk-XV pull request #22
Opened 2020-02-11 11:50 UTC by chuyii

ひとまず
・ダイアログだす
・ボタン押されるまでまつ
・押されたら数字を表示して1秒後に消える
・出た目を返す
を実装しました。
命名センスがないのでいいのがあったら教えてください。
アニメーションは保留。
（ボタン押されるまでアニメーションするってなるとwaitforなんちゃらをもう一個つくったほうがいいのかね？）

close #18

2020-02-11 12:39 UTC, GarAcT commented
（ボタンが押されるまでというとむしろWaitForButtonClickedを軸に作れそうな気がしなくもない）

2020-02-11 12:43 UTC, chuyii commented
アニメーション終了フラグ作っておいて
StartCoroutine(数字アニメーション)して、
yield return new WaitForButtonClicked()
でボタン押されるまで待ってからフラグ立てる

みたいなイメージであってるかな

2020-02-11 13:37 UTC, GarAcT commented on Assets/Scripts/SimpleStageManager.cs
> +        rollDiceButton.gameObject.SetActive(true);
この辺は次呼ばれた時のための初期化？
（だとしたら）panel.SetActive(true)の前に置いてあるほうが自然な気がする

2020-02-11 13:40 UTC, GarAcT commented
とりあえずアニメーションの件については、 #15 に置いといて後まわしで良いでしょう

2020-02-11 15:09 UTC, chuyii commented
アニメーションの件おっけー。
初期化処理だけ先頭に回しておきます。

2020-02-11 15:25 UTC, proelbtn commented on Assets/Scripts/SimpleStageManager.cs
> +        Button rollDiceButton = rollDicePanel.transform.GetChild(0).transform.GetComponent<Button>();
これやっぱりもっといい方法で取得したいね（あまりきれいな方法ではないので）

2020-02-11 15:32 UTC, GarAcT commented on Assets/Scripts/SimpleStageManager.cs
> +        Button rollDiceButton = rollDicePanel.transform.GetChild(0).transform.GetComponent<Button>();
一応こんなものもあるが（こっちもあまりきれいでもないけど）…
https://docs.unity3d.com/ja/current/ScriptReference/GameObject.GetComponentsInChildren.html

2020-02-11 15:32 UTC, proelbtn requested changes

2020-02-11 15:32 UTC, proelbtn commented on Assets/Scripts/SimpleStageManager.cs
> +        numbertext.text = "";
not activeにしてからtextを消去するより、activeにする前に初期化をするほうが自然だと思う

2020-02-11 15:32 UTC, proelbtn commented on Assets/Scripts/SimpleStageManager.cs
> +        numbertext.text = "";
あ、同じことが書いてあった。。。ごめんよ。。。

2020-02-11 15:32 UTC, proelbtn commented on Assets/Scripts/SimpleStageManager.cs
> +        Button rollDiceButton = rollDicePanel.transform.GetChild(0).transform.GetComponent<Button>();
```
Text numbertext = rollDicePanel.transform.Find("Number").transform.GetComponent<Text>();
```

これと同様にするほうがいい気がする

2020-02-11 15:32 UTC, proelbtn commented on Assets/Scripts/SimpleStageManager.cs
> +        Button rollDiceButton = rollDicePanel.transform.GetChild(0).transform.GetComponent<Button>();
もしくはこんな感じのwrapper functionを用意するのがいい気がする。だけど、僕はこんな文字列を比較する実装はあまり素敵とは思えない。普通はenumで数値比較とかでできるべき（Unityがこんなイケてないことになるとは思わないのできっとなんかありそうだけどとりあえずGetChild(0)するのは良くないので修正してほしいです）

```
GameObject GetChildWithName(GameObject obj, string name) {
     Transform trans = obj.transform;
     Transform childTrans = trans. Find(name);
     if (childTrans != null) {
         return childTrans.gameObject;
     } else {
         return null;
     }
 }
```

https://answers.unity.com/questions/1355787/find-children-in-parent.html

2020-02-11 15:34 UTC, GarAcT commented
あとSceneのConflictでちゃったのでちょっとめんどくさいね…

2020-02-11 15:35 UTC, proelbtn commented
まぁ普通にローカルでmergeしてcommitすればいいよ

2020-02-11 15:37 UTC, GarAcT commented
それはそうというかそうするしかないんだけどScene弄るのめんどくちーという話

2020-02-11 15:41 UTC, proelbtn commented
両方とも取り込めばよさそう（diffを読むかぎりinspectorでどれを指定しているのかを決めているだけなので両方実装されたコードでは両方取り込むだけでconflictが解決すると思います）

2020-02-11 15:41 UTC, proelbtn commented
別にweb editorでresolveさせてもいいけどどうする？

2020-02-11 15:42 UTC, GarAcT commented
んーじゃやっといて（一応ローカルで動作確認しといて）

2020-02-12 00:39 UTC, GarAcT commented
![image](https://user-images.githubusercontent.com/16851181/74292484-7b1c7480-4d7b-11ea-8f51-b87ab64c5d2d.png)
こんな感じでボタンがはみ出ることがあるけどまあ #15 行きだな

2020-02-12 00:42 UTC, Semi11 commented on Assets/Scripts/SimpleStageManager.cs
> +        int number = Random.Range(0, 6) + 1;
出る目引数で指定できるようにしといた方が便利そう（最小，最大）
デバッグ用に任意の目出るサイコロとかいるか？

2020-02-12 00:58 UTC, GarAcT approved these changes

2020-02-12 01:00 UTC, GarAcT commented
GetChildの辺りはほかでも使ってるし、wrapperを作るなら汎用できるやつが欲しい
まあとりあえず時間もないし今はこれで良いかななどと

2020-02-12 01:06 UTC, GarAcT commented
（wrapperについて取り掛かるなら別途Issueを開けよう…）

2020-02-12 02:45 UTC, GarAcT approved these changes

2020-02-12 02:46 UTC, Semi11 approved these changes

2020-02-12 10:18 UTC, proelbtn approved these changes

2020-02-12 10:18 UTC, merged