[update] implement GetSquares
ilovejikkenjisshu/ILJJ_Mk-XV pull request #25
Opened 2020-02-12 10:48 UTC by proelbtn

refs: https://github.com/ilovejikkenjisshu/ILJJ_Mk-XV/issues/10#issuecomment-584689592

2020-02-12 11:15 UTC, GarAcT reviewed
Tagを付けるのも無しではないなと思ったけど、Square型はこれ以外に使わないだろうし型で指定して取ってくるほうが手間がかからないのではと思った
https://docs.unity3d.com/ja/current/ScriptReference/GameObject.GetComponentsInChildren.html

2020-02-12 13:20 UTC, GarAcT commented
まって、今になって気づいたけど、Prefabに変更はないの？

2020-02-12 13:23 UTC, GarAcT commented
すべてのSquareにTagを付けるなら、PrefabにTagを付けてそれをすべてに適用するはずだけど…

2020-02-12 13:27 UTC, GarAcT requested changes
SquareのPrefabがUntaggedのまま

2020-02-12 14:11 UTC, proelbtn commented
あー完全に理解した

2020-02-12 14:28 UTC, proelbtn commented
fixed

2020-02-12 23:34 UTC, GarAcT approved these changes

2020-02-15 04:14 UTC, Semi11 approved these changes

2020-02-15 04:15 UTC, merged