[add] ダイスロールテキストアニメーションを追加
ilovejikkenjisshu/ILJJ_Mk-XV pull request #27
Opened 2020-02-12 11:47 UTC by Semi11

とりあえず毎フレームランダムに数字が表示されるアニメーション．
ボタン押したらアニメーション停止する．

2020-02-12 11:57 UTC, chuyii requested changes

2020-02-12 11:57 UTC, chuyii commented on Assets/Scripts/SimpleStageManager.cs
> +    public IEnumerator PlayDiceAnimation(int min, int max)
PlayDiceAnimationってprivateでもいい気がする

2020-02-12 13:08 UTC, GarAcT requested changes

2020-02-12 13:08 UTC, GarAcT commented on Assets/Scripts/SimpleStageManager.cs
> +        Text numbertext = rollDicePanel.transform.Find("Number").transform.GetComponent<Text>();
このTextは外から渡してきた方がいいと思った（毎フレームFindするのかなり無駄そう）

2020-02-12 13:08 UTC, GarAcT commented on Assets/Scripts/SimpleStageManager.cs
> +        int number;
numberの宣言位置があまりにも奇妙では…？

2020-02-12 13:17 UTC, chuyii commented on Assets/Scripts/SimpleStageManager.cs
> +        Text numbertext = rollDicePanel.transform.Find("Number").transform.GetComponent<Text>();
一回findして持ってきたらStopCoroutineされるまでwhile無限ループに入ってるから無駄ではなさそう。
似たようなアニメーションを他の場所でも使うなら外からTextを渡してもいいけど、サイコロのアニメーションにしか使わないならこのままでもいいのでは。

2020-02-12 13:18 UTC, chuyii approved these changes

2020-02-12 13:28 UTC, GarAcT commented on Assets/Scripts/SimpleStageManager.cs
> +        Text numbertext = rollDicePanel.transform.Find("Number").transform.GetComponent<Text>();
んあーそっか

2020-02-16 05:37 UTC, GarAcT approved these changes

2020-02-16 05:37 UTC, merged