タイトルシーンの実装
ilovejikkenjisshu/ILJJ_Mk-XV pull request #7
Opened 2019-11-19 15:29 UTC by chuyii

タイトルシーンを実装。
Utilクラスは[このページ](https://qiita.com/2dgames_jp/items/11bb76167fb44bb5af5f)で配布されているのを少し変更して利用。
ボタンを押すとSimpleStageSceneに遷移する。

close #5

2019-11-19 15:58 UTC, proelbtn commented
closes: #5

2019-11-19 23:55 UTC, GarAcT commented on Assets/Scripts/Util.cs
> +public class Util {
まだちゃんと見てないけど `Util` という名前な微妙な気がするゾ

2019-11-20 00:25 UTC, GarAcT reviewed
何もないSceneにスクリプトで生成してる感じ？
予めSceneに置いておく方が楽な気がしますが…

2019-11-20 02:34 UTC, GarAcT requested changes
Scene中心の実装でやり直しということで

2019-11-20 02:37 UTC, closed without merging